#ENC[AES256_GCM,data:DwNB1QEikrIbDBzqYN26W8GBiboM,iv:ANwV3lQElqDloY31BB4xWJN5534R4AfKFAyuEi/vo5Q=,tag:YX4+WaEIsCWEkz8OBv822g==,type:comment]
#ENC[AES256_GCM,data:3u1OEe4bbWXRWDkm+rirJZDD87G2xIEsGGheupY=,iv:h129WSy9Mb3xUUifuCB1Z4McQ5cLK5svFBhwF46vWMg=,tag:eJcg6I8GFL8BctJAQcNyNA==,type:comment]
#
do_token: ENC[AES256_GCM,data:yrNtCKMKWN8N//zcpG400o0Mpeq2vSOuavQTT5rvzz6iajPwnX+8h+0kX0egwjFjZjC8eOtWg5el+niHkAUbcZTVcRY6fgs=,iv:DzeZkZpXa8yN4FcuaEG7vxudqa0rWdGk6njfz9WeLSk=,tag:v1GZ4+9r7mxgsU2gOPJFsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-16T12:55:38Z"
    mac: ENC[AES256_GCM,data:0bN0KleguMswgIMScR0U3UeK48okyQubylSw6ucG2c5K3kyAcXAUxf4eSkU8WSmOzEK1GYx8XDDbu+bE/CccilW1IMGLbKtQYyGT+lrmvnuXtvBKNKzF8x8LvMBZh5JGfquIGKllk/el0TNpY26QTmppJPbUoD4AsOZETxClc/k=,iv:l3Xzk5MKA91ytCRmDPFYL8JPoUugo9iQ+EdRuEhgatQ=,tag:lD2UKKQg9/uXjBWhkgONnA==,type:str]
    pgp:
        - created_at: "2025-03-08T13:24:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2fheYx7el0jARAAqBH+8zmscGiq5+6w5jQD45k6NO1Zv2GhFpkM1+7ziCQg
            khNv9oGc2+79ugpA17heHNbpQAs0AH9vVT02vg+tIjdSgyiJY6lT37K4DAg80TVP
            Lo61uBEbF38LlmyAs8k/OigmCBTnyAyQVcrhnNGOSCf+dzvzXoakozNMVCUzJGV6
            i+AaSp2XdeC1kbw2u8S4ay2TyG+XWNszFgn5b2COLZOW0aldIFQSCHVWERFHxCiS
            WJl3nugf2btHWZqBwWgq/5NiRNtYvJH3fpUKxAVtyFsCrzjmR7p9Ojv8sy+9NOLe
            OaYWrqtjTc9GZaFWHtpyFB6qRV38SmOZkAqJG+w9vsEgLJTtUNOqRCjzQdRHCbTI
            4WN/J898fkrPKxwROR6HUQRg6eif404ioYRc96ua9MCnZAsnFULk8iEob7AOYfHn
            r9gda0p0HMwc0aiNx2lXHpVGOqoWl7ByXC2W5+lqppL8Zu1SlqLjzqnGtKaYOK/G
            o32bJBCDz6cOGb48x447ccnyjQR5ir3pLHqZ/WknsoZX9v5KBFjlRmVwV7c6Bjs0
            N/GjDB5Fs9pODSe7j/uLh6ZE7dbZXt+hGdyyBtQb1cIWNBOz5ZeeuV2C26J7+a4t
            ih6rdMXO1AFpz3wAf+BrbvPclzAK/IZMM42IsPZIdnm/sWKLXNIxzMPj6h8ruBzS
            XgFrPZBi7J+LIF/0wzGnAt8J8vTaKB/R23em9H26tZwvRgF1RlcE616EtPQM51Hp
            A7mbHcy7AOdv6JniAdOt184w7hW/ZdLwShguVFzHfrC8JXNd+enS2msHpJjkU6U=
            =m+JL
            -----END PGP MESSAGE-----
          fp: CBEB44B1E9FD46F3C052496E0C43126B9A9CD273
    unencrypted_suffix: _unencrypted
    version: 3.9.3
