# https://taskfile.dev

version: "3"

# TODO: find out why .envrc is not being sourced
env:
  TF_VAR_tenancy_ocid:
    sh: jc --ini <~/.oci/config | jq -r .DEFAULT.tenancy
  TF_VAR_region:
    sh: jc --ini <~/.oci/config | jq -r .DEFAULT.region

silent: true

tasks:
  default:
    cmds:
      - task --list

  control-plane:
    desc: "Create a control plane bastion session"
    dir: "{{ .USER_WORKING_DIR }}/configs/blacksd/oci-bastion-sessions/oke-control-plane/"
    cmds:
      - terragrunt apply -auto-approve
      - echo "Now you can set your working directory to $PWD/control-plane and start using the session. Please refer to the README.md file for more information."

  workers:
    desc: "Create a workers bastion session"
    dir: "{{ .USER_WORKING_DIR }}/configs/blacksd/oci-bastion-sessions/oke-workers/"
    cmds:
      - terragrunt apply -auto-approve
      - echo "Now you can set your working directory to $PWD/workers and start using the sessions. Please refer to the README.md file for more information."
